mr: reworked application to API requests
reversersed/zyfra pull request #6
Opened 2024-11-09 13:47 UTC by reversersed

2024-11-09 14:12 UTC, Ressorrrrra commented
no

2024-11-09 14:17 UTC, Ressorrrrra reviewed
постное масло

2024-11-09 14:17 UTC, Ressorrrrra commented on .github/workflows/testing.yml
>  on:
ААА? ЧЁ? НЕ СЛЫШУ???

2024-11-12 21:19 UTC, abogdanov37 requested changes

2024-11-12 21:19 UTC, abogdanov37 commented on docs/swagger.json
> +{
Это судя по всему результат работы генератора

2024-11-12 21:19 UTC, abogdanov37 commented on docs/swagger.yaml
> +basePath: /api/
Это видимо тоже генерируется. если так то зачем они в репе. Мы в свое время хранили такие веще в репе чтобы сделать dev portal и там публиковать доку

2024-11-12 21:19 UTC, abogdanov37 commented on internal/handlers/handlers.go
> +// @Failure      404  {object}  models.RequestError "User was not found or password is incorrect"
лучше 401 unauthorized

2024-11-12 21:19 UTC, abogdanov37 commented on internal/handlers/handlers.go
> +	c.Status(http.StatusNoContent)
Лучше 200 он более широко применяется

2024-11-24 16:12 UTC, merged